version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres         # Имя пользователя (по умолчанию postgres)
      POSTGRES_PASSWORD: 12345 # Пароль
      POSTGRES_DB: my_capital_db       # Имя создаваемой базы данных
    ports:
    - "5433:5432"  # Слева порт компа (меняем), справа порт контейнера (не трогаем)
    volumes:
      - postgres_data:/var/lib/postgresql/data # Точка монтирования для сохранения данных

volumes:
  postgres_data:
